import type { Metadata } from 'next';
import '@/app/styles/globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { manrope } from '@/app/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${manrope.className} ${manrope.className} antialiased`}>
        <Header />
        <div className='container'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
